# -*- coding: utf-8 -*-
"""0515_기본문제_by_코랩.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1mriQbLYxsXEf5Op0m-FPgHT7OXGwNJX7

X보다 작은 수
https://www.acmicpc.net/problem/10871
>> 문제가 쉬우신 분들은 입력 부분에 조건들을 예외처리 하는 코드도 작성해보세요!
ex ) 1 ≤ N, X ≤ 10,000 부분 이외에는 “1 ~ 10,000 사이 숫자를 입력해주세요” 와 같이 오류 출력이 나올 수 있도록 작성하기

< 참고 자료 >
https://dojang.io/mod/page/view.php?id=2400
https://wikidocs.net/105490
https://velog.io/@yeonu/%ED%8C%8C%EC%9D%B4%EC%8D%AC-%EC%98%88%EC%99%B8%EC%B2%98%EB%A6%AC
"""

#X보다 작은 수 https://www.acmicpc.net/problem/10871

#N과 X 입력
N, X = map(int, input().split())
#리스트 입력받기
lst = list(map(int, input().split()))
#반복문으로 X보다 작은 수만 출력
print(*(i for i in lst if i < X ))

#예외처리 적용
try:
    #N과 X 입력
    N, X = map(int, input().split())
    #조건문과 raise 함수를 이용 예외 발생
    if 1 >= N or X >= 10000 : raise Exception("1~10000사이 숫자를 입력해주세요.")
    #리스트 입력받기
    lst = list(map(int, input().split()))
    #반복문으로 X보다 작은 수만 출력
    print(*(i for i in lst if i < X ))
except Exception as e:
    print(e)

"""곱셈 
https://www.acmicpc.net/problem/2588

문제를 풀면서 코드가 많이 길어진다면, 더 간단한 코드 구현이 가능한지와 함수가 존재 하는지 생각하면서 작성해보세요~!
"""

#입력받기
A, B = int(input()), int(input())
#인덱싱을 사용해서 자릿수 곱해주기
for i in range(1, len(str(B))+1):
    print(A* int(str(B)[-i]))
print(A*B)

